POST http://localhost:5000/api/products HTTP/1.1
Content-Type: application/json

{
  "imagePath": ["path/to/image1.jpg", "path/to/image2.jpg"],
  "name": "Dildo de Silicona",
  "description": "Dildo de silicona suave y flexible, ideal para una experiencia placentera.",
  "price": 29.99,
  "title": "Dildo de Silicona",
  "priceBuy": "29.99",
  "sizeBralette": ["S", "M", "L"],
  "sizePanty": ["S", "M", "L"],
  "color": ["Rojo", "Negro", "Rosa"],
  "amountMl": 100,
  "category": "67622f71dc29fbdb9e34b7de"  // Reemplaza con un ID válido de la categoría
}
###
GET http://localhost:5000/api/products HTTP/1.1

###
DELETE http://localhost:5000/api/products/66cfec5b83b40db3453400fa HTTP/1.1