POST http://localhost:5000/api/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTMyMmM0YzBmYjgyYTNiMzFlMzJjYSIsInJvbCI6IkNMSUVOVEUiLCJuYW1lIjoiSnVhbiIsImxhc3ROYW1lIjoiUMOpcmV6IiwiZW1haWwiOiJmYWVzcGFuYWdAdXF2aXJ0dWFsLmVkdS5jbyIsImlhdCI6MTc0MjcwNDYwMSwiZXhwIjoxNzQyNzkxMDAxfQ.xwvEhCDziRPq73qcLt2VU04Eaiu8Cvr7FLRpTNqji60

{
  "name": "Bombitas",
  "description": "Categoria para dildos en todos los materiales como: pvc, silicona etc",
  "state" : false
}
###
GET http://localhost:5000/api/categories HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTMyMmM0YzBmYjgyYTNiMzFlMzJjYSIsInJvbCI6IkNMSUVOVEUiLCJuYW1lIjoiSnVhbiIsImxhc3ROYW1lIjoiUMOpcmV6IiwiZW1haWwiOiJmYWVzcGFuYWdAdXF2aXJ0dWFsLmVkdS5jbyIsImlhdCI6MTc0MzY0NDU4NSwiZXhwIjoxNzQzNzMwOTg1fQ.uhtg0gWueWbAGstWpxdlnT-KMMZ1tCAv7hhFYmifj1o

###
GET http://localhost:5000/api/categories/66e1a02a02077c2ceb031741 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTMyMmM0YzBmYjgyYTNiMzFlMzJjYSIsInJvbCI6IkNMSUVOVEUiLCJuYW1lIjoiSnVhbiIsImxhc3ROYW1lIjoiUMOpcmV6IiwiZW1haWwiOiJmYWVzcGFuYWdAdXF2aXJ0dWFsLmVkdS5jbyIsImlhdCI6MTc0MjcwNDYwMSwiZXhwIjoxNzQyNzkxMDAxfQ.xwvEhCDziRPq73qcLt2VU04Eaiu8Cvr7FLRpTNqji60
###
PUT http://localhost:5000/api/categories/66e1a02a02077c2ceb031741 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTMyMmM0YzBmYjgyYTNiMzFlMzJjYSIsInJvbCI6IkNMSUVOVEUiLCJuYW1lIjoiSnVhbiIsImxhc3ROYW1lIjoiUMOpcmV6IiwiZW1haWwiOiJmYWVzcGFuYWdAdXF2aXJ0dWFsLmVkdS5jbyIsImlhdCI6MTc0MjcwNDYwMSwiZXhwIjoxNzQyNzkxMDAxfQ.xwvEhCDziRPq73qcLt2VU04Eaiu8Cvr7FLRpTNqji60


{
  "name": "New Category Name",
  "description": "Updated description of the category",
  "estado":1
}
###
DELETE http://localhost:5000/api/categories/66df7990d532a0895383994f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTMyMmM0YzBmYjgyYTNiMzFlMzJjYSIsInJvbCI6IkNMSUVOVEUiLCJuYW1lIjoiSnVhbiIsImxhc3ROYW1lIjoiUMOpcmV6IiwiZW1haWwiOiJmYWVzcGFuYWdAdXF2aXJ0dWFsLmVkdS5jbyIsImlhdCI6MTc0MjcwNDYwMSwiZXhwIjoxNzQyNzkxMDAxfQ.xwvEhCDziRPq73qcLt2VU04Eaiu8Cvr7FLRpTNqji60

//Delete masivo
###
POST  http://localhost:5000/api/categories/delete-bulk HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTMyMmM0YzBmYjgyYTNiMzFlMzJjYSIsInJvbCI6IkNMSUVOVEUiLCJuYW1lIjoiSnVhbiIsImxhc3ROYW1lIjoiUMOpcmV6IiwiZW1haWwiOiJmYWVzcGFuYWdAdXF2aXJ0dWFsLmVkdS5jbyIsImlhdCI6MTczNDM4MDY1NywiZXhwIjoxNzM0NDY3MDU3fQ._gEMzIirbvor1x3M4B4k4K0-EIjRZNsACj3RjFWhyXY

{
"ids" : [
  "66e1a02a02077c2ceb031741",
  "675e1a0bc7eb959e289ed95e",
  "675e22ee7b3314d5a842906f",
  "675e25a147044e53a31c7618",
  "675e40bc3a2b6380c604a420",
  "6760924a33fe2de017db0794",
  "676097a17335da48e407db51",
  "67609817dd69ea65268d5841",
  "6760984bdd69ea65268d5846",
  "6760991edd69ea65268d584b",
  "6760999cdd69ea65268d584e",
  "67609a67dd69ea65268d5853",
  "67609bc27335da48e407db59",
  "67609c177335da48e407db5e",
  "67609c3f7335da48e407db64",
  "67609cb67335da48e407db67",
  "6761726176af29afc3dd65ce"
]}
