###
POST http://localhost:5000/api/user HTTP/1.1
Content-Type: application/json

{
  "rol": "CLIENTE",
  "name": "Juan",
  "lastName": "Pérez",
  "email": "faespanag@uqvirtual.edu.co",
  "phone": "1234567890",
  "city": "Bogotá",
  "deparment": "Cundinamarca",
  "address": "Calle 123 #45-67",
  "birthDate": "1990-05-15",
  "registrationDate": "2024-09-10",
  "password": "miSegura123"
}
###
GET http://localhost:5000/api/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTMyMmM0YzBmYjgyYTNiMzFlMzJjYSIsInJvbCI6IkNMSUVOVEUiLCJuYW1lIjoiSnVhbiIsImxhc3ROYW1lIjoiUMOpcmV6IiwiZW1haWwiOiJmYWVzcGFuYWdAdXF2aXJ0dWFsLmVkdS5jbyIsImlhdCI6MTcyNjE2MTYyOSwiZXhwIjoxNzI2MjQ4MDI5fQ.VLCzVsgBt6sBjsfRIAigaSdtwDWn9PBIHicBlgn-M98

###
POST http://localhost:5000/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "faespanag@uqvirtual.edu.co",
  "password":"miSegura123"
}

###
DELETE http://localhost:5000/api/user/66e1b726a2cdb36e2495be02 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTFiODczNzY5MjY2NjdiZjVjZjg0YyIsInJvbCI6IkNMSUVOVEUiLCJuYW1lIjoiSnVhbiIsImxhc3ROYW1lIjoiUMOpcmV6IiwiZW1haWwiOiJmYWVzcGFuYWdAdXF2aXJ0dWFsLmVkdS5jbyIsImlhdCI6MTcyNjA2OTYxMiwiZXhwIjoxNzI2MTU2MDEyfQ.hGVSGNjFZdX1pAvJHyzdmZmdd6M4IloEFdnwXraahh0

###
PUT http://localhost:5000/api/user/66e1b87376926667bf5cf84c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTFiODczNzY5MjY2NjdiZjVjZjg0YyIsInJvbCI6IkNMSUVOVEUiLCJuYW1lIjoiSnVhbiIsImxhc3ROYW1lIjoiUMOpcmV6IiwiZW1haWwiOiJmYWVzcGFuYWdAdXF2aXJ0dWFsLmVkdS5jbyIsImlhdCI6MTcyNjA2OTYxMiwiZXhwIjoxNzI2MTU2MDEyfQ.hGVSGNjFZdX1pAvJHyzdmZmdd6M4IloEFdnwXraahh0

{
  "rol": "ADMIN",
  "name": "Carlos",
  "lastName": "Gómez",
  "email": "carlos.gomez@example.com",
  "phone": "9876543210",
  "city": "Medellín",
  "deparment": "Antioquia",
  "modifyDate": "2024-09-15T12:34:56Z",
  "address": "Avenida 50 #32-14",
  "birthDate": "1985-10-22",
  "password": "NuevaContraseña123",
  "state": 1,
  "cart": [
    {
      "productId": "60c72b2f5f1b2c001f9e11b0",
      "quantity": 2
    },
    {
      "productId": "60c72b2f5f1b2c001f9e11b1",
      "quantity": 1
    }
  ]
}
// "cart": null


